/* THANKS SDK :))))), this file remap SDL keycode / keysym */

#ifndef __SSGE_KEYBOARD_H__
#define __SSGE_KEYBOARD_H__

#define _SCANCODE_TO_KEYCODE(X) (X | 1<<30)

enum _SSGE_Scancode {
    SSGE_SCANCODE_UNKNOWN = 0,

    /**
     *  \name Usage page 0x07
     *
     *  These values are from usage page 0x07 (USB keyboard page).
     */
    /* @{ */

    SSGE_SCANCODE_A = 4,
    SSGE_SCANCODE_B = 5,
    SSGE_SCANCODE_C = 6,
    SSGE_SCANCODE_D = 7,
    SSGE_SCANCODE_E = 8,
    SSGE_SCANCODE_F = 9,
    SSGE_SCANCODE_G = 10,
    SSGE_SCANCODE_H = 11,
    SSGE_SCANCODE_I = 12,
    SSGE_SCANCODE_J = 13,
    SSGE_SCANCODE_K = 14,
    SSGE_SCANCODE_L = 15,
    SSGE_SCANCODE_M = 16,
    SSGE_SCANCODE_N = 17,
    SSGE_SCANCODE_O = 18,
    SSGE_SCANCODE_P = 19,
    SSGE_SCANCODE_Q = 20,
    SSGE_SCANCODE_R = 21,
    SSGE_SCANCODE_S = 22,
    SSGE_SCANCODE_T = 23,
    SSGE_SCANCODE_U = 24,
    SSGE_SCANCODE_V = 25,
    SSGE_SCANCODE_W = 26,
    SSGE_SCANCODE_X = 27,
    SSGE_SCANCODE_Y = 28,
    SSGE_SCANCODE_Z = 29,

    SSGE_SCANCODE_1 = 30,
    SSGE_SCANCODE_2 = 31,
    SSGE_SCANCODE_3 = 32,
    SSGE_SCANCODE_4 = 33,
    SSGE_SCANCODE_5 = 34,
    SSGE_SCANCODE_6 = 35,
    SSGE_SCANCODE_7 = 36,
    SSGE_SCANCODE_8 = 37,
    SSGE_SCANCODE_9 = 38,
    SSGE_SCANCODE_0 = 39,

    SSGE_SCANCODE_RETURN = 40,
    SSGE_SCANCODE_ESCAPE = 41,
    SSGE_SCANCODE_BACKSPACE = 42,
    SSGE_SCANCODE_TAB = 43,
    SSGE_SCANCODE_SPACE = 44,

    SSGE_SCANCODE_MINUS = 45,
    SSGE_SCANCODE_EQUALS = 46,
    SSGE_SCANCODE_LEFTBRACKET = 47,
    SSGE_SCANCODE_RIGHTBRACKET = 48,
    SSGE_SCANCODE_BACKSLASH = 49, /**< Located at the lower left of the return
                                  *   key on ISO keyboards and at the right end
                                  *   of the QWERTY row on ANSI keyboards.
                                  *   Produces REVERSE SOLIDUS (backslash) and
                                  *   VERTICAL LINE in a US layout, REVERSE
                                  *   SOLIDUS and VERTICAL LINE in a UK Mac
                                  *   layout, NUMBER SIGN and TILDE in a UK
                                  *   Windows layout, DOLLAR SIGN and POUND SIGN
                                  *   in a Swiss German layout, NUMBER SIGN and
                                  *   APOSTROPHE in a German layout, GRAVE
                                  *   ACCENT and POUND SIGN in a French Mac
                                  *   layout, and ASTERISK and MICRO SIGN in a
                                  *   French Windows layout.
                                  */
    SSGE_SCANCODE_NONUSHASH = 50, /**< ISO USB keyboards actually use this code
                                  *   instead of 49 for the same key, but all
                                  *   OSes I've seen treat the two codes
                                  *   identically. So, as an implementor, unless
                                  *   your keyboard generates both of those
                                  *   codes and your OS treats them differently,
                                  *   you should generate SSGE_SCANCODE_BACKSLASH
                                  *   instead of this code. As a user, you
                                  *   should not rely on this code because SDL
                                  *   will never generate it with most (all?)
                                  *   keyboards.
                                  */
    SSGE_SCANCODE_SEMICOLON = 51,
    SSGE_SCANCODE_APOSTROPHE = 52,
    SSGE_SCANCODE_GRAVE = 53, /**< Located in the top left corner (on both ANSI
                              *   and ISO keyboards). Produces GRAVE ACCENT and
                              *   TILDE in a US Windows layout and in US and UK
                              *   Mac layouts on ANSI keyboards, GRAVE ACCENT
                              *   and NOT SIGN in a UK Windows layout, SECTION
                              *   SIGN and PLUS-MINUS SIGN in US and UK Mac
                              *   layouts on ISO keyboards, SECTION SIGN and
                              *   DEGREE SIGN in a Swiss German layout (Mac:
                              *   only on ISO keyboards), CIRCUMFLEX ACCENT and
                              *   DEGREE SIGN in a German layout (Mac: only on
                              *   ISO keyboards), SUPERSCRIPT TWO and TILDE in a
                              *   French Windows layout, COMMERCIAL AT and
                              *   NUMBER SIGN in a French Mac layout on ISO
                              *   keyboards, and LESS-THAN SIGN and GREATER-THAN
                              *   SIGN in a Swiss German, German, or French Mac
                              *   layout on ANSI keyboards.
                              */
    SSGE_SCANCODE_COMMA = 54,
    SSGE_SCANCODE_PERIOD = 55,
    SSGE_SCANCODE_SLASH = 56,

    SSGE_SCANCODE_CAPSLOCK = 57,

    SSGE_SCANCODE_F1 = 58,
    SSGE_SCANCODE_F2 = 59,
    SSGE_SCANCODE_F3 = 60,
    SSGE_SCANCODE_F4 = 61,
    SSGE_SCANCODE_F5 = 62,
    SSGE_SCANCODE_F6 = 63,
    SSGE_SCANCODE_F7 = 64,
    SSGE_SCANCODE_F8 = 65,
    SSGE_SCANCODE_F9 = 66,
    SSGE_SCANCODE_F10 = 67,
    SSGE_SCANCODE_F11 = 68,
    SSGE_SCANCODE_F12 = 69,

    SSGE_SCANCODE_PRINTSCREEN = 70,
    SSGE_SCANCODE_SCROLLLOCK = 71,
    SSGE_SCANCODE_PAUSE = 72,
    SSGE_SCANCODE_INSERT = 73, /**< insert on PC, help on some Mac keyboards (but
                                   does send code 73, not 117) */
    SSGE_SCANCODE_HOME = 74,
    SSGE_SCANCODE_PAGEUP = 75,
    SSGE_SCANCODE_DELETE = 76,
    SSGE_SCANCODE_END = 77,
    SSGE_SCANCODE_PAGEDOWN = 78,
    SSGE_SCANCODE_RIGHT = 79,
    SSGE_SCANCODE_LEFT = 80,
    SSGE_SCANCODE_DOWN = 81,
    SSGE_SCANCODE_UP = 82,

    SSGE_SCANCODE_NUMLOCKCLEAR = 83, /**< num lock on PC, clear on Mac keyboards
                                     */
    SSGE_SCANCODE_KP_DIVIDE = 84,
    SSGE_SCANCODE_KP_MULTIPLY = 85,
    SSGE_SCANCODE_KP_MINUS = 86,
    SSGE_SCANCODE_KP_PLUS = 87,
    SSGE_SCANCODE_KP_ENTER = 88,
    SSGE_SCANCODE_KP_1 = 89,
    SSGE_SCANCODE_KP_2 = 90,
    SSGE_SCANCODE_KP_3 = 91,
    SSGE_SCANCODE_KP_4 = 92,
    SSGE_SCANCODE_KP_5 = 93,
    SSGE_SCANCODE_KP_6 = 94,
    SSGE_SCANCODE_KP_7 = 95,
    SSGE_SCANCODE_KP_8 = 96,
    SSGE_SCANCODE_KP_9 = 97,
    SSGE_SCANCODE_KP_0 = 98,
    SSGE_SCANCODE_KP_PERIOD = 99,

    SSGE_SCANCODE_NONUSBACKSLASH = 100, /**< This is the additional key that ISO
                                        *   keyboards have over ANSI ones,
                                        *   located between left shift and Y.
                                        *   Produces GRAVE ACCENT and TILDE in a
                                        *   US or UK Mac layout, REVERSE SOLIDUS
                                        *   (backslash) and VERTICAL LINE in a
                                        *   US or UK Windows layout, and
                                        *   LESS-THAN SIGN and GREATER-THAN SIGN
                                        *   in a Swiss German, German, or French
                                        *   layout. */
    SSGE_SCANCODE_APPLICATION = 101, /**< windows contextual menu, compose */
    SSGE_SCANCODE_POWER = 102, /**< The USB document says this is a status flag,
                               *   not a physical key - but some Mac keyboards
                               *   do have a power key. */
    SSGE_SCANCODE_KP_EQUALS = 103,
    SSGE_SCANCODE_F13 = 104,
    SSGE_SCANCODE_F14 = 105,
    SSGE_SCANCODE_F15 = 106,
    SSGE_SCANCODE_F16 = 107,
    SSGE_SCANCODE_F17 = 108,
    SSGE_SCANCODE_F18 = 109,
    SSGE_SCANCODE_F19 = 110,
    SSGE_SCANCODE_F20 = 111,
    SSGE_SCANCODE_F21 = 112,
    SSGE_SCANCODE_F22 = 113,
    SSGE_SCANCODE_F23 = 114,
    SSGE_SCANCODE_F24 = 115,
    SSGE_SCANCODE_EXECUTE = 116,
    SSGE_SCANCODE_HELP = 117,    /**< AL Integrated Help Center */
    SSGE_SCANCODE_MENU = 118,    /**< Menu (show menu) */
    SSGE_SCANCODE_SELECT = 119,
    SSGE_SCANCODE_STOP = 120,    /**< AC Stop */
    SSGE_SCANCODE_AGAIN = 121,   /**< AC Redo/Repeat */
    SSGE_SCANCODE_UNDO = 122,    /**< AC Undo */
    SSGE_SCANCODE_CUT = 123,     /**< AC Cut */
    SSGE_SCANCODE_COPY = 124,    /**< AC Copy */
    SSGE_SCANCODE_PASTE = 125,   /**< AC Paste */
    SSGE_SCANCODE_FIND = 126,    /**< AC Find */
    SSGE_SCANCODE_MUTE = 127,
    SSGE_SCANCODE_VOLUMEUP = 128,
    SSGE_SCANCODE_VOLUMEDOWN = 129,
/* not sure whether there's a reason to enable these */
/*     SSGE_SCANCODE_LOCKINGCAPSLOCK = 130,  */
/*     SSGE_SCANCODE_LOCKINGNUMLOCK = 131, */
/*     SSGE_SCANCODE_LOCKINGSCROLLLOCK = 132, */
    SSGE_SCANCODE_KP_COMMA = 133,
    SSGE_SCANCODE_KP_EQUALSAS400 = 134,

    SSGE_SCANCODE_INTERNATIONAL1 = 135, /**< used on Asian keyboards, see
                                            footnotes in USB doc */
    SSGE_SCANCODE_INTERNATIONAL2 = 136,
    SSGE_SCANCODE_INTERNATIONAL3 = 137, /**< Yen */
    SSGE_SCANCODE_INTERNATIONAL4 = 138,
    SSGE_SCANCODE_INTERNATIONAL5 = 139,
    SSGE_SCANCODE_INTERNATIONAL6 = 140,
    SSGE_SCANCODE_INTERNATIONAL7 = 141,
    SSGE_SCANCODE_INTERNATIONAL8 = 142,
    SSGE_SCANCODE_INTERNATIONAL9 = 143,
    SSGE_SCANCODE_LANG1 = 144, /**< Hangul/English toggle */
    SSGE_SCANCODE_LANG2 = 145, /**< Hanja conversion */
    SSGE_SCANCODE_LANG3 = 146, /**< Katakana */
    SSGE_SCANCODE_LANG4 = 147, /**< Hiragana */
    SSGE_SCANCODE_LANG5 = 148, /**< Zenkaku/Hankaku */
    SSGE_SCANCODE_LANG6 = 149, /**< reserved */
    SSGE_SCANCODE_LANG7 = 150, /**< reserved */
    SSGE_SCANCODE_LANG8 = 151, /**< reserved */
    SSGE_SCANCODE_LANG9 = 152, /**< reserved */

    SSGE_SCANCODE_ALTERASE = 153,    /**< Erase-Eaze */
    SSGE_SCANCODE_SYSREQ = 154,
    SSGE_SCANCODE_CANCEL = 155,      /**< AC Cancel */
    SSGE_SCANCODE_CLEAR = 156,
    SSGE_SCANCODE_PRIOR = 157,
    SSGE_SCANCODE_RETURN2 = 158,
    SSGE_SCANCODE_SEPARATOR = 159,
    SSGE_SCANCODE_OUT = 160,
    SSGE_SCANCODE_OPER = 161,
    SSGE_SCANCODE_CLEARAGAIN = 162,
    SSGE_SCANCODE_CRSEL = 163,
    SSGE_SCANCODE_EXSEL = 164,

    SSGE_SCANCODE_KP_00 = 176,
    SSGE_SCANCODE_KP_000 = 177,
    SSGE_SCANCODE_THOUSANDSSEPARATOR = 178,
    SSGE_SCANCODE_DECIMALSEPARATOR = 179,
    SSGE_SCANCODE_CURRENCYUNIT = 180,
    SSGE_SCANCODE_CURRENCYSUBUNIT = 181,
    SSGE_SCANCODE_KP_LEFTPAREN = 182,
    SSGE_SCANCODE_KP_RIGHTPAREN = 183,
    SSGE_SCANCODE_KP_LEFTBRACE = 184,
    SSGE_SCANCODE_KP_RIGHTBRACE = 185,
    SSGE_SCANCODE_KP_TAB = 186,
    SSGE_SCANCODE_KP_BACKSPACE = 187,
    SSGE_SCANCODE_KP_A = 188,
    SSGE_SCANCODE_KP_B = 189,
    SSGE_SCANCODE_KP_C = 190,
    SSGE_SCANCODE_KP_D = 191,
    SSGE_SCANCODE_KP_E = 192,
    SSGE_SCANCODE_KP_F = 193,
    SSGE_SCANCODE_KP_XOR = 194,
    SSGE_SCANCODE_KP_POWER = 195,
    SSGE_SCANCODE_KP_PERCENT = 196,
    SSGE_SCANCODE_KP_LESS = 197,
    SSGE_SCANCODE_KP_GREATER = 198,
    SSGE_SCANCODE_KP_AMPERSAND = 199,
    SSGE_SCANCODE_KP_DBLAMPERSAND = 200,
    SSGE_SCANCODE_KP_VERTICALBAR = 201,
    SSGE_SCANCODE_KP_DBLVERTICALBAR = 202,
    SSGE_SCANCODE_KP_COLON = 203,
    SSGE_SCANCODE_KP_HASH = 204,
    SSGE_SCANCODE_KP_SPACE = 205,
    SSGE_SCANCODE_KP_AT = 206,
    SSGE_SCANCODE_KP_EXCLAM = 207,
    SSGE_SCANCODE_KP_MEMSTORE = 208,
    SSGE_SCANCODE_KP_MEMRECALL = 209,
    SSGE_SCANCODE_KP_MEMCLEAR = 210,
    SSGE_SCANCODE_KP_MEMADD = 211,
    SSGE_SCANCODE_KP_MEMSUBTRACT = 212,
    SSGE_SCANCODE_KP_MEMMULTIPLY = 213,
    SSGE_SCANCODE_KP_MEMDIVIDE = 214,
    SSGE_SCANCODE_KP_PLUSMINUS = 215,
    SSGE_SCANCODE_KP_CLEAR = 216,
    SSGE_SCANCODE_KP_CLEARENTRY = 217,
    SSGE_SCANCODE_KP_BINARY = 218,
    SSGE_SCANCODE_KP_OCTAL = 219,
    SSGE_SCANCODE_KP_DECIMAL = 220,
    SSGE_SCANCODE_KP_HEXADECIMAL = 221,

    SSGE_SCANCODE_LCTRL = 224,
    SSGE_SCANCODE_LSHIFT = 225,
    SSGE_SCANCODE_LALT = 226, /**< alt, option */
    SSGE_SCANCODE_LGUI = 227, /**< windows, command (apple), meta */
    SSGE_SCANCODE_RCTRL = 228,
    SSGE_SCANCODE_RSHIFT = 229,
    SSGE_SCANCODE_RALT = 230, /**< alt gr, option */
    SSGE_SCANCODE_RGUI = 231, /**< windows, command (apple), meta */

    SSGE_SCANCODE_MODE = 257,    /**< I'm not sure if this is really not covered
                                 *   by any of the above, but since there's a
                                 *   special KMOD_MODE for it I'm adding it here
                                 */

    /* @} *//* Usage page 0x07 */

    /**
     *  \name Usage page 0x0C
     *
     *  These values are mapped from usage page 0x0C (USB consumer page).
     *  See https://usb.org/sites/default/files/hut1_2.pdf
     *
     *  There are way more keys in the spec than we can represent in the
     *  current scancode range, so pick the ones that commonly come up in
     *  real world usage.
     */
    /* @{ */

    SSGE_SCANCODE_AUDIONEXT = 258,
    SSGE_SCANCODE_AUDIOPREV = 259,
    SSGE_SCANCODE_AUDIOSTOP = 260,
    SSGE_SCANCODE_AUDIOPLAY = 261,
    SSGE_SCANCODE_AUDIOMUTE = 262,
    SSGE_SCANCODE_MEDIASELECT = 263,
    SSGE_SCANCODE_WWW = 264,             /**< AL Internet Browser */
    SSGE_SCANCODE_MAIL = 265,
    SSGE_SCANCODE_CALCULATOR = 266,      /**< AL Calculator */
    SSGE_SCANCODE_COMPUTER = 267,
    SSGE_SCANCODE_AC_SEARCH = 268,       /**< AC Search */
    SSGE_SCANCODE_AC_HOME = 269,         /**< AC Home */
    SSGE_SCANCODE_AC_BACK = 270,         /**< AC Back */
    SSGE_SCANCODE_AC_FORWARD = 271,      /**< AC Forward */
    SSGE_SCANCODE_AC_STOP = 272,         /**< AC Stop */
    SSGE_SCANCODE_AC_REFRESH = 273,      /**< AC Refresh */
    SSGE_SCANCODE_AC_BOOKMARKS = 274,    /**< AC Bookmarks */

    /* @} *//* Usage page 0x0C */

    /**
     *  \name Walther keys
     *
     *  These are values that Christian Walther added (for mac keyboard?).
     */
    /* @{ */

    SSGE_SCANCODE_BRIGHTNESSDOWN = 275,
    SSGE_SCANCODE_BRIGHTNESSUP = 276,
    SSGE_SCANCODE_DISPLAYSWITCH = 277, /**< display mirroring/dual display
                                           switch, video mode switch */
    SSGE_SCANCODE_KBDILLUMTOGGLE = 278,
    SSGE_SCANCODE_KBDILLUMDOWN = 279,
    SSGE_SCANCODE_KBDILLUMUP = 280,
    SSGE_SCANCODE_EJECT = 281,
    SSGE_SCANCODE_SLEEP = 282,           /**< SC System Sleep */

    SSGE_SCANCODE_APP1 = 283,
    SSGE_SCANCODE_APP2 = 284,

    /* @} *//* Walther keys */

    /**
     *  \name Usage page 0x0C (additional media keys)
     *
     *  These values are mapped from usage page 0x0C (USB consumer page).
     */
    /* @{ */

    SSGE_SCANCODE_AUDIOREWIND = 285,
    SSGE_SCANCODE_AUDIOFASTFORWARD = 286,

    /* @} *//* Usage page 0x0C (additional media keys) */

    /**
     *  \name Mobile keys
     *
     *  These are values that are often used on mobile phones.
     */
    /* @{ */

    SSGE_SCANCODE_SOFTLEFT = 287, /**< Usually situated below the display on phones and
                                      used as a multi-function feature key for selecting
                                      a software defined function shown on the bottom left
                                      of the display. */
    SSGE_SCANCODE_SOFTRIGHT = 288, /**< Usually situated below the display on phones and
                                       used as a multi-function feature key for selecting
                                       a software defined function shown on the bottom right
                                       of the display. */
    SSGE_SCANCODE_CALL = 289, /**< Used for accepting phone calls. */
    SSGE_SCANCODE_ENDCALL = 290, /**< Used for rejecting phone calls. */

    /* @} *//* Mobile keys */

    /* Add any other keys here. */

    SSGE_KEY_NUM_SCANCODES = 512 /**< not a key, just marks the number of scancodes
                                 for array bounds */
};

typedef enum
{
    SSGE_KEY_UNKNOWN = 0,

    SSGE_KEY_RETURN = '\r',
    SSGE_KEY_ESCAPE = '\x1B',
    SSGE_KEY_BACKSPACE = '\b',
    SSGE_KEY_TAB = '\t',
    SSGE_KEY_SPACE = ' ',
    SSGE_KEY_EXCLAIM = '!',
    SSGE_KEY_QUOTEDBL = '"',
    SSGE_KEY_HASH = '#',
    SSGE_KEY_PERCENT = '%',
    SSGE_KEY_DOLLAR = '$',
    SSGE_KEY_AMPERSAND = '&',
    SSGE_KEY_QUOTE = '\'',
    SSGE_KEY_LEFTPAREN = '(',
    SSGE_KEY_RIGHTPAREN = ')',
    SSGE_KEY_ASTERISK = '*',
    SSGE_KEY_PLUS = '+',
    SSGE_KEY_COMMA = ',',
    SSGE_KEY_MINUS = '-',
    SSGE_KEY_PERIOD = '.',
    SSGE_KEY_SLASH = '/',
    SSGE_KEY_0 = '0',
    SSGE_KEY_1 = '1',
    SSGE_KEY_2 = '2',
    SSGE_KEY_3 = '3',
    SSGE_KEY_4 = '4',
    SSGE_KEY_5 = '5',
    SSGE_KEY_6 = '6',
    SSGE_KEY_7 = '7',
    SSGE_KEY_8 = '8',
    SSGE_KEY_9 = '9',
    SSGE_KEY_COLON = ':',
    SSGE_KEY_SEMICOLON = ';',
    SSGE_KEY_LESS = '<',
    SSGE_KEY_EQUALS = '=',
    SSGE_KEY_GREATER = '>',
    SSGE_KEY_QUESTION = '?',
    SSGE_KEY_AT = '@',

    /*
       Skip uppercase letters
     */

    SSGE_KEY_LEFTBRACKET = '[',
    SSGE_KEY_BACKSLASH = '\\',
    SSGE_KEY_RIGHTBRACKET = ']',
    SSGE_KEY_CARET = '^',
    SSGE_KEY_UNDERSCORE = '_',
    SSGE_KEY_BACKQUOTE = '`',
    SSGE_KEY_a = 'a',
    SSGE_KEY_b = 'b',
    SSGE_KEY_c = 'c',
    SSGE_KEY_d = 'd',
    SSGE_KEY_e = 'e',
    SSGE_KEY_f = 'f',
    SSGE_KEY_g = 'g',
    SSGE_KEY_h = 'h',
    SSGE_KEY_i = 'i',
    SSGE_KEY_j = 'j',
    SSGE_KEY_k = 'k',
    SSGE_KEY_l = 'l',
    SSGE_KEY_m = 'm',
    SSGE_KEY_n = 'n',
    SSGE_KEY_o = 'o',
    SSGE_KEY_p = 'p',
    SSGE_KEY_q = 'q',
    SSGE_KEY_r = 'r',
    SSGE_KEY_s = 's',
    SSGE_KEY_t = 't',
    SSGE_KEY_u = 'u',
    SSGE_KEY_v = 'v',
    SSGE_KEY_w = 'w',
    SSGE_KEY_x = 'x',
    SSGE_KEY_y = 'y',
    SSGE_KEY_z = 'z',

    SSGE_KEY_CAPSLOCK = _SCANCODE_TO_KEYCODE(SSGE_SCANCODE_CAPSLOCK),

    SSGE_KEY_F1 = _SCANCODE_TO_KEYCODE(SSGE_SCANCODE_F1),
    SSGE_KEY_F2 = _SCANCODE_TO_KEYCODE(SSGE_SCANCODE_F2),
    SSGE_KEY_F3 = _SCANCODE_TO_KEYCODE(SSGE_SCANCODE_F3),
    SSGE_KEY_F4 = _SCANCODE_TO_KEYCODE(SSGE_SCANCODE_F4),
    SSGE_KEY_F5 = _SCANCODE_TO_KEYCODE(SSGE_SCANCODE_F5),
    SSGE_KEY_F6 = _SCANCODE_TO_KEYCODE(SSGE_SCANCODE_F6),
    SSGE_KEY_F7 = _SCANCODE_TO_KEYCODE(SSGE_SCANCODE_F7),
    SSGE_KEY_F8 = _SCANCODE_TO_KEYCODE(SSGE_SCANCODE_F8),
    SSGE_KEY_F9 = _SCANCODE_TO_KEYCODE(SSGE_SCANCODE_F9),
    SSGE_KEY_F10 = _SCANCODE_TO_KEYCODE(SSGE_SCANCODE_F10),
    SSGE_KEY_F11 = _SCANCODE_TO_KEYCODE(SSGE_SCANCODE_F11),
    SSGE_KEY_F12 = _SCANCODE_TO_KEYCODE(SSGE_SCANCODE_F12),

    SSGE_KEY_PRINTSCREEN = _SCANCODE_TO_KEYCODE(SSGE_SCANCODE_PRINTSCREEN),
    SSGE_KEY_SCROLLLOCK = _SCANCODE_TO_KEYCODE(SSGE_SCANCODE_SCROLLLOCK),
    SSGE_KEY_PAUSE = _SCANCODE_TO_KEYCODE(SSGE_SCANCODE_PAUSE),
    SSGE_KEY_INSERT = _SCANCODE_TO_KEYCODE(SSGE_SCANCODE_INSERT),
    SSGE_KEY_HOME = _SCANCODE_TO_KEYCODE(SSGE_SCANCODE_HOME),
    SSGE_KEY_PAGEUP = _SCANCODE_TO_KEYCODE(SSGE_SCANCODE_PAGEUP),
    SSGE_KEY_DELETE = '\x7F',
    SSGE_KEY_END = _SCANCODE_TO_KEYCODE(SSGE_SCANCODE_END),
    SSGE_KEY_PAGEDOWN = _SCANCODE_TO_KEYCODE(SSGE_SCANCODE_PAGEDOWN),
    SSGE_KEY_RIGHT = _SCANCODE_TO_KEYCODE(SSGE_SCANCODE_RIGHT),
    SSGE_KEY_LEFT = _SCANCODE_TO_KEYCODE(SSGE_SCANCODE_LEFT),
    SSGE_KEY_DOWN = _SCANCODE_TO_KEYCODE(SSGE_SCANCODE_DOWN),
    SSGE_KEY_UP = _SCANCODE_TO_KEYCODE(SSGE_SCANCODE_UP),

    SSGE_KEY_NUMLOCKCLEAR = _SCANCODE_TO_KEYCODE(SSGE_SCANCODE_NUMLOCKCLEAR),
    SSGE_KEY_KP_DIVIDE = _SCANCODE_TO_KEYCODE(SSGE_SCANCODE_KP_DIVIDE),
    SSGE_KEY_KP_MULTIPLY = _SCANCODE_TO_KEYCODE(SSGE_SCANCODE_KP_MULTIPLY),
    SSGE_KEY_KP_MINUS = _SCANCODE_TO_KEYCODE(SSGE_SCANCODE_KP_MINUS),
    SSGE_KEY_KP_PLUS = _SCANCODE_TO_KEYCODE(SSGE_SCANCODE_KP_PLUS),
    SSGE_KEY_KP_ENTER = _SCANCODE_TO_KEYCODE(SSGE_SCANCODE_KP_ENTER),
    SSGE_KEY_KP_1 = _SCANCODE_TO_KEYCODE(SSGE_SCANCODE_KP_1),
    SSGE_KEY_KP_2 = _SCANCODE_TO_KEYCODE(SSGE_SCANCODE_KP_2),
    SSGE_KEY_KP_3 = _SCANCODE_TO_KEYCODE(SSGE_SCANCODE_KP_3),
    SSGE_KEY_KP_4 = _SCANCODE_TO_KEYCODE(SSGE_SCANCODE_KP_4),
    SSGE_KEY_KP_5 = _SCANCODE_TO_KEYCODE(SSGE_SCANCODE_KP_5),
    SSGE_KEY_KP_6 = _SCANCODE_TO_KEYCODE(SSGE_SCANCODE_KP_6),
    SSGE_KEY_KP_7 = _SCANCODE_TO_KEYCODE(SSGE_SCANCODE_KP_7),
    SSGE_KEY_KP_8 = _SCANCODE_TO_KEYCODE(SSGE_SCANCODE_KP_8),
    SSGE_KEY_KP_9 = _SCANCODE_TO_KEYCODE(SSGE_SCANCODE_KP_9),
    SSGE_KEY_KP_0 = _SCANCODE_TO_KEYCODE(SSGE_SCANCODE_KP_0),
    SSGE_KEY_KP_PERIOD = _SCANCODE_TO_KEYCODE(SSGE_SCANCODE_KP_PERIOD),

    SSGE_KEY_APPLICATION = _SCANCODE_TO_KEYCODE(SSGE_SCANCODE_APPLICATION),
    SSGE_KEY_POWER = _SCANCODE_TO_KEYCODE(SSGE_SCANCODE_POWER),
    SSGE_KEY_KP_EQUALS = _SCANCODE_TO_KEYCODE(SSGE_SCANCODE_KP_EQUALS),
    SSGE_KEY_F13 = _SCANCODE_TO_KEYCODE(SSGE_SCANCODE_F13),
    SSGE_KEY_F14 = _SCANCODE_TO_KEYCODE(SSGE_SCANCODE_F14),
    SSGE_KEY_F15 = _SCANCODE_TO_KEYCODE(SSGE_SCANCODE_F15),
    SSGE_KEY_F16 = _SCANCODE_TO_KEYCODE(SSGE_SCANCODE_F16),
    SSGE_KEY_F17 = _SCANCODE_TO_KEYCODE(SSGE_SCANCODE_F17),
    SSGE_KEY_F18 = _SCANCODE_TO_KEYCODE(SSGE_SCANCODE_F18),
    SSGE_KEY_F19 = _SCANCODE_TO_KEYCODE(SSGE_SCANCODE_F19),
    SSGE_KEY_F20 = _SCANCODE_TO_KEYCODE(SSGE_SCANCODE_F20),
    SSGE_KEY_F21 = _SCANCODE_TO_KEYCODE(SSGE_SCANCODE_F21),
    SSGE_KEY_F22 = _SCANCODE_TO_KEYCODE(SSGE_SCANCODE_F22),
    SSGE_KEY_F23 = _SCANCODE_TO_KEYCODE(SSGE_SCANCODE_F23),
    SSGE_KEY_F24 = _SCANCODE_TO_KEYCODE(SSGE_SCANCODE_F24),
    SSGE_KEY_EXECUTE = _SCANCODE_TO_KEYCODE(SSGE_SCANCODE_EXECUTE),
    SSGE_KEY_HELP = _SCANCODE_TO_KEYCODE(SSGE_SCANCODE_HELP),
    SSGE_KEY_MENU = _SCANCODE_TO_KEYCODE(SSGE_SCANCODE_MENU),
    SSGE_KEY_SELECT = _SCANCODE_TO_KEYCODE(SSGE_SCANCODE_SELECT),
    SSGE_KEY_STOP = _SCANCODE_TO_KEYCODE(SSGE_SCANCODE_STOP),
    SSGE_KEY_AGAIN = _SCANCODE_TO_KEYCODE(SSGE_SCANCODE_AGAIN),
    SSGE_KEY_UNDO = _SCANCODE_TO_KEYCODE(SSGE_SCANCODE_UNDO),
    SSGE_KEY_CUT = _SCANCODE_TO_KEYCODE(SSGE_SCANCODE_CUT),
    SSGE_KEY_COPY = _SCANCODE_TO_KEYCODE(SSGE_SCANCODE_COPY),
    SSGE_KEY_PASTE = _SCANCODE_TO_KEYCODE(SSGE_SCANCODE_PASTE),
    SSGE_KEY_FIND = _SCANCODE_TO_KEYCODE(SSGE_SCANCODE_FIND),
    SSGE_KEY_MUTE = _SCANCODE_TO_KEYCODE(SSGE_SCANCODE_MUTE),
    SSGE_KEY_VOLUMEUP = _SCANCODE_TO_KEYCODE(SSGE_SCANCODE_VOLUMEUP),
    SSGE_KEY_VOLUMEDOWN = _SCANCODE_TO_KEYCODE(SSGE_SCANCODE_VOLUMEDOWN),
    SSGE_KEY_KP_COMMA = _SCANCODE_TO_KEYCODE(SSGE_SCANCODE_KP_COMMA),
    SSGE_KEY_KP_EQUALSAS400 =
        _SCANCODE_TO_KEYCODE(SSGE_SCANCODE_KP_EQUALSAS400),

    SSGE_KEY_ALTERASE = _SCANCODE_TO_KEYCODE(SSGE_SCANCODE_ALTERASE),
    SSGE_KEY_SYSREQ = _SCANCODE_TO_KEYCODE(SSGE_SCANCODE_SYSREQ),
    SSGE_KEY_CANCEL = _SCANCODE_TO_KEYCODE(SSGE_SCANCODE_CANCEL),
    SSGE_KEY_CLEAR = _SCANCODE_TO_KEYCODE(SSGE_SCANCODE_CLEAR),
    SSGE_KEY_PRIOR = _SCANCODE_TO_KEYCODE(SSGE_SCANCODE_PRIOR),
    SSGE_KEY_RETURN2 = _SCANCODE_TO_KEYCODE(SSGE_SCANCODE_RETURN2),
    SSGE_KEY_SEPARATOR = _SCANCODE_TO_KEYCODE(SSGE_SCANCODE_SEPARATOR),
    SSGE_KEY_OUT = _SCANCODE_TO_KEYCODE(SSGE_SCANCODE_OUT),
    SSGE_KEY_OPER = _SCANCODE_TO_KEYCODE(SSGE_SCANCODE_OPER),
    SSGE_KEY_CLEARAGAIN = _SCANCODE_TO_KEYCODE(SSGE_SCANCODE_CLEARAGAIN),
    SSGE_KEY_CRSEL = _SCANCODE_TO_KEYCODE(SSGE_SCANCODE_CRSEL),
    SSGE_KEY_EXSEL = _SCANCODE_TO_KEYCODE(SSGE_SCANCODE_EXSEL),

    SSGE_KEY_KP_00 = _SCANCODE_TO_KEYCODE(SSGE_SCANCODE_KP_00),
    SSGE_KEY_KP_000 = _SCANCODE_TO_KEYCODE(SSGE_SCANCODE_KP_000),
    SSGE_KEY_THOUSANDSSEPARATOR =
        _SCANCODE_TO_KEYCODE(SSGE_SCANCODE_THOUSANDSSEPARATOR),
    SSGE_KEY_DECIMALSEPARATOR =
        _SCANCODE_TO_KEYCODE(SSGE_SCANCODE_DECIMALSEPARATOR),
    SSGE_KEY_CURRENCYUNIT = _SCANCODE_TO_KEYCODE(SSGE_SCANCODE_CURRENCYUNIT),
    SSGE_KEY_CURRENCYSUBUNIT =
        _SCANCODE_TO_KEYCODE(SSGE_SCANCODE_CURRENCYSUBUNIT),
    SSGE_KEY_KP_LEFTPAREN = _SCANCODE_TO_KEYCODE(SSGE_SCANCODE_KP_LEFTPAREN),
    SSGE_KEY_KP_RIGHTPAREN = _SCANCODE_TO_KEYCODE(SSGE_SCANCODE_KP_RIGHTPAREN),
    SSGE_KEY_KP_LEFTBRACE = _SCANCODE_TO_KEYCODE(SSGE_SCANCODE_KP_LEFTBRACE),
    SSGE_KEY_KP_RIGHTBRACE = _SCANCODE_TO_KEYCODE(SSGE_SCANCODE_KP_RIGHTBRACE),
    SSGE_KEY_KP_TAB = _SCANCODE_TO_KEYCODE(SSGE_SCANCODE_KP_TAB),
    SSGE_KEY_KP_BACKSPACE = _SCANCODE_TO_KEYCODE(SSGE_SCANCODE_KP_BACKSPACE),
    SSGE_KEY_KP_A = _SCANCODE_TO_KEYCODE(SSGE_SCANCODE_KP_A),
    SSGE_KEY_KP_B = _SCANCODE_TO_KEYCODE(SSGE_SCANCODE_KP_B),
    SSGE_KEY_KP_C = _SCANCODE_TO_KEYCODE(SSGE_SCANCODE_KP_C),
    SSGE_KEY_KP_D = _SCANCODE_TO_KEYCODE(SSGE_SCANCODE_KP_D),
    SSGE_KEY_KP_E = _SCANCODE_TO_KEYCODE(SSGE_SCANCODE_KP_E),
    SSGE_KEY_KP_F = _SCANCODE_TO_KEYCODE(SSGE_SCANCODE_KP_F),
    SSGE_KEY_KP_XOR = _SCANCODE_TO_KEYCODE(SSGE_SCANCODE_KP_XOR),
    SSGE_KEY_KP_POWER = _SCANCODE_TO_KEYCODE(SSGE_SCANCODE_KP_POWER),
    SSGE_KEY_KP_PERCENT = _SCANCODE_TO_KEYCODE(SSGE_SCANCODE_KP_PERCENT),
    SSGE_KEY_KP_LESS = _SCANCODE_TO_KEYCODE(SSGE_SCANCODE_KP_LESS),
    SSGE_KEY_KP_GREATER = _SCANCODE_TO_KEYCODE(SSGE_SCANCODE_KP_GREATER),
    SSGE_KEY_KP_AMPERSAND = _SCANCODE_TO_KEYCODE(SSGE_SCANCODE_KP_AMPERSAND),
    SSGE_KEY_KP_DBLAMPERSAND =
        _SCANCODE_TO_KEYCODE(SSGE_SCANCODE_KP_DBLAMPERSAND),
    SSGE_KEY_KP_VERTICALBAR =
        _SCANCODE_TO_KEYCODE(SSGE_SCANCODE_KP_VERTICALBAR),
    SSGE_KEY_KP_DBLVERTICALBAR =
        _SCANCODE_TO_KEYCODE(SSGE_SCANCODE_KP_DBLVERTICALBAR),
    SSGE_KEY_KP_COLON = _SCANCODE_TO_KEYCODE(SSGE_SCANCODE_KP_COLON),
    SSGE_KEY_KP_HASH = _SCANCODE_TO_KEYCODE(SSGE_SCANCODE_KP_HASH),
    SSGE_KEY_KP_SPACE = _SCANCODE_TO_KEYCODE(SSGE_SCANCODE_KP_SPACE),
    SSGE_KEY_KP_AT = _SCANCODE_TO_KEYCODE(SSGE_SCANCODE_KP_AT),
    SSGE_KEY_KP_EXCLAM = _SCANCODE_TO_KEYCODE(SSGE_SCANCODE_KP_EXCLAM),
    SSGE_KEY_KP_MEMSTORE = _SCANCODE_TO_KEYCODE(SSGE_SCANCODE_KP_MEMSTORE),
    SSGE_KEY_KP_MEMRECALL = _SCANCODE_TO_KEYCODE(SSGE_SCANCODE_KP_MEMRECALL),
    SSGE_KEY_KP_MEMCLEAR = _SCANCODE_TO_KEYCODE(SSGE_SCANCODE_KP_MEMCLEAR),
    SSGE_KEY_KP_MEMADD = _SCANCODE_TO_KEYCODE(SSGE_SCANCODE_KP_MEMADD),
    SSGE_KEY_KP_MEMSUBTRACT =
        _SCANCODE_TO_KEYCODE(SSGE_SCANCODE_KP_MEMSUBTRACT),
    SSGE_KEY_KP_MEMMULTIPLY =
        _SCANCODE_TO_KEYCODE(SSGE_SCANCODE_KP_MEMMULTIPLY),
    SSGE_KEY_KP_MEMDIVIDE = _SCANCODE_TO_KEYCODE(SSGE_SCANCODE_KP_MEMDIVIDE),
    SSGE_KEY_KP_PLUSMINUS = _SCANCODE_TO_KEYCODE(SSGE_SCANCODE_KP_PLUSMINUS),
    SSGE_KEY_KP_CLEAR = _SCANCODE_TO_KEYCODE(SSGE_SCANCODE_KP_CLEAR),
    SSGE_KEY_KP_CLEARENTRY = _SCANCODE_TO_KEYCODE(SSGE_SCANCODE_KP_CLEARENTRY),
    SSGE_KEY_KP_BINARY = _SCANCODE_TO_KEYCODE(SSGE_SCANCODE_KP_BINARY),
    SSGE_KEY_KP_OCTAL = _SCANCODE_TO_KEYCODE(SSGE_SCANCODE_KP_OCTAL),
    SSGE_KEY_KP_DECIMAL = _SCANCODE_TO_KEYCODE(SSGE_SCANCODE_KP_DECIMAL),
    SSGE_KEY_KP_HEXADECIMAL =
        _SCANCODE_TO_KEYCODE(SSGE_SCANCODE_KP_HEXADECIMAL),

    SSGE_KEY_LCTRL = _SCANCODE_TO_KEYCODE(SSGE_SCANCODE_LCTRL),
    SSGE_KEY_LSHIFT = _SCANCODE_TO_KEYCODE(SSGE_SCANCODE_LSHIFT),
    SSGE_KEY_LALT = _SCANCODE_TO_KEYCODE(SSGE_SCANCODE_LALT),
    SSGE_KEY_LGUI = _SCANCODE_TO_KEYCODE(SSGE_SCANCODE_LGUI),
    SSGE_KEY_RCTRL = _SCANCODE_TO_KEYCODE(SSGE_SCANCODE_RCTRL),
    SSGE_KEY_RSHIFT = _SCANCODE_TO_KEYCODE(SSGE_SCANCODE_RSHIFT),
    SSGE_KEY_RALT = _SCANCODE_TO_KEYCODE(SSGE_SCANCODE_RALT),
    SSGE_KEY_RGUI = _SCANCODE_TO_KEYCODE(SSGE_SCANCODE_RGUI),

    SSGE_KEY_MODE = _SCANCODE_TO_KEYCODE(SSGE_SCANCODE_MODE),

    SSGE_KEY_AUDIONEXT = _SCANCODE_TO_KEYCODE(SSGE_SCANCODE_AUDIONEXT),
    SSGE_KEY_AUDIOPREV = _SCANCODE_TO_KEYCODE(SSGE_SCANCODE_AUDIOPREV),
    SSGE_KEY_AUDIOSTOP = _SCANCODE_TO_KEYCODE(SSGE_SCANCODE_AUDIOSTOP),
    SSGE_KEY_AUDIOPLAY = _SCANCODE_TO_KEYCODE(SSGE_SCANCODE_AUDIOPLAY),
    SSGE_KEY_AUDIOMUTE = _SCANCODE_TO_KEYCODE(SSGE_SCANCODE_AUDIOMUTE),
    SSGE_KEY_MEDIASELECT = _SCANCODE_TO_KEYCODE(SSGE_SCANCODE_MEDIASELECT),
    SSGE_KEY_WWW = _SCANCODE_TO_KEYCODE(SSGE_SCANCODE_WWW),
    SSGE_KEY_MAIL = _SCANCODE_TO_KEYCODE(SSGE_SCANCODE_MAIL),
    SSGE_KEY_CALCULATOR = _SCANCODE_TO_KEYCODE(SSGE_SCANCODE_CALCULATOR),
    SSGE_KEY_COMPUTER = _SCANCODE_TO_KEYCODE(SSGE_SCANCODE_COMPUTER),
    SSGE_KEY_AC_SEARCH = _SCANCODE_TO_KEYCODE(SSGE_SCANCODE_AC_SEARCH),
    SSGE_KEY_AC_HOME = _SCANCODE_TO_KEYCODE(SSGE_SCANCODE_AC_HOME),
    SSGE_KEY_AC_BACK = _SCANCODE_TO_KEYCODE(SSGE_SCANCODE_AC_BACK),
    SSGE_KEY_AC_FORWARD = _SCANCODE_TO_KEYCODE(SSGE_SCANCODE_AC_FORWARD),
    SSGE_KEY_AC_STOP = _SCANCODE_TO_KEYCODE(SSGE_SCANCODE_AC_STOP),
    SSGE_KEY_AC_REFRESH = _SCANCODE_TO_KEYCODE(SSGE_SCANCODE_AC_REFRESH),
    SSGE_KEY_AC_BOOKMARKS = _SCANCODE_TO_KEYCODE(SSGE_SCANCODE_AC_BOOKMARKS),

    SSGE_KEY_BRIGHTNESSDOWN =
        _SCANCODE_TO_KEYCODE(SSGE_SCANCODE_BRIGHTNESSDOWN),
    SSGE_KEY_BRIGHTNESSUP = _SCANCODE_TO_KEYCODE(SSGE_SCANCODE_BRIGHTNESSUP),
    SSGE_KEY_DISPLAYSWITCH = _SCANCODE_TO_KEYCODE(SSGE_SCANCODE_DISPLAYSWITCH),
    SSGE_KEY_KBDILLUMTOGGLE =
        _SCANCODE_TO_KEYCODE(SSGE_SCANCODE_KBDILLUMTOGGLE),
    SSGE_KEY_KBDILLUMDOWN = _SCANCODE_TO_KEYCODE(SSGE_SCANCODE_KBDILLUMDOWN),
    SSGE_KEY_KBDILLUMUP = _SCANCODE_TO_KEYCODE(SSGE_SCANCODE_KBDILLUMUP),
    SSGE_KEY_EJECT = _SCANCODE_TO_KEYCODE(SSGE_SCANCODE_EJECT),
    SSGE_KEY_SLEEP = _SCANCODE_TO_KEYCODE(SSGE_SCANCODE_SLEEP),
    SSGE_KEY_APP1 = _SCANCODE_TO_KEYCODE(SSGE_SCANCODE_APP1),
    SSGE_KEY_APP2 = _SCANCODE_TO_KEYCODE(SSGE_SCANCODE_APP2),

    SSGE_KEY_AUDIOREWIND = _SCANCODE_TO_KEYCODE(SSGE_SCANCODE_AUDIOREWIND),
    SSGE_KEY_AUDIOFASTFORWARD = _SCANCODE_TO_KEYCODE(SSGE_SCANCODE_AUDIOFASTFORWARD),

    SSGE_KEY_SOFTLEFT = _SCANCODE_TO_KEYCODE(SSGE_SCANCODE_SOFTLEFT),
    SSGE_KEY_SOFTRIGHT = _SCANCODE_TO_KEYCODE(SSGE_SCANCODE_SOFTRIGHT),
    SSGE_KEY_CALL = _SCANCODE_TO_KEYCODE(SSGE_SCANCODE_CALL),
    SSGE_KEY_ENDCALL = _SCANCODE_TO_KEYCODE(SSGE_SCANCODE_ENDCALL)
} SSGE_KEY_KeyCode;

#endif // __SSGE_KEYBOARD_H__